version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - video-call-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - video-call-network

networks:
  video-call-network:
    driver: bridge