export const aboutStyles = {
  container: {
    minHeight: '90vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    py: 4,
  },
  background: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: '-10rem',
    right: '-10rem',
    width: '20rem',
    height: '20rem',
    background: 'rgba(255, 255, 255, 0.1)',
    borderRadius: '50%',
    filter: 'blur(3rem)',
    animation: 'pulse 4s ease-in-out infinite',
  },
  circle2: {
    position: 'absolute',
    bottom: '-10rem',
    left: '-10rem',
    width: '24rem',
    height: '24rem',
    background: 'rgba(59, 130, 246, 0.2)',
    borderRadius: '50%',
    filter: 'blur(3rem)',
    animation: 'pulse 5s ease-in-out infinite 1s',
  },
  circle3: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '16rem',
    height: '16rem',
    background: 'rgba(234, 179, 8, 0.1)',
    borderRadius: '50%',
    filter: 'blur(2rem)',
    animation: 'ping 6s ease-in-out infinite',
  },
  header: {
    textAlign: 'center',
    mb: 6,
  },
  logoContainer: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    background: 'linear-gradient(to right, #3b82f6, #9333ea)',
    borderRadius: '50%',
    mb: 4,
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
  },
  title: {
    fontWeight: 'bold',
    color: 'white',
    background: 'linear-gradient(to right, #ffffff, #bfdbfe)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    mb: 2,
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: 'medium',
  },
  description: {
    color: 'rgba(255, 255, 255, 0.9)',
    maxWidth: 600,
    mx: 'auto',
    mb: 8,
    lineHeight: 1.8,
    fontSize: '1.1rem',
  },
  features: {
    mb: 8,
  },
  featureCard: {
    background: 'rgba(255, 255, 255, 0.1)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: '16px',
    transition: 'transform 0.3s, box-shadow 0.3s',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
    },
  },
  featureContent: {
    textAlign: 'center',
    p: 4,
  },
  featureIcon: {
    mb: 2,
  },
  featureTitle: {
    color: 'white',
    fontWeight: 'medium',
    mb: 1,
  },
  featureDescription: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  ctaContainer: {
    textAlign: 'center',
    mb: 6,
  },
  ctaButton: {
    background: 'linear-gradient(to right, #3b82f6, #9333ea)',
    color: 'white',
    fontWeight: 'medium',
    px: 4,
    py: 2,
    mt: 2,
    borderRadius: '16px',
    textTransform: 'none',
    fontSize: '1.1rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
    '&:hover': {
      background: 'linear-gradient(to right, #2563eb, #7e22ce)',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.3)',
      transform: 'translateY(-2px)',
    },
    transition: 'all 0.3s',
  },
  connections: {
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    mt: 4,
  },
  '@keyframes pulse': {
    '0%, 100%': { transform: 'scale(1)', opacity: 1 },
    '50%': { transform: 'scale(1.2)', opacity: 0.7 },
  },
  '@keyframes ping': {
    '0%, 100%': { transform: 'scale(1)', opacity: 1 },
    '50%': { transform: 'scale(1.4)', opacity: 0.5 },
  },
};