export const videoCallStyles = {
  container: {
    minHeight: '100vh',
    padding: { xs: '16px', sm: '24px', md: '32px' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  header: {
    textAlign: 'center',
    mb: { xs: 3, sm: 4 },
    background: 'rgba(15, 23, 42, 0.7)',
    backdropFilter: 'blur(10px)',
    borderRadius: '16px',
    p: { xs: 2, sm: 3 },
    border: '1px solid rgba(255, 255, 255, 0.2)',
    maxWidth: '800px',
    width: '100%',
  },
  logoContainer: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    background: 'linear-gradient(to right, #3b82f6, #9333ea)',
    borderRadius: '50%',
    mb: 2,
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
  },
  headerTitle: {
    fontWeight: 700,
    color: '#ffffff',
    background: 'linear-gradient(to right, #ffffff, #bfdbfe)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  headerSubtitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    mt: 1,
  },
  userInfo: {
    display: 'flex',
    justifyContent: 'center',
    gap: 4,
    mt: 2,
    flexWrap: 'wrap',
  },
  userText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: { xs: '0.9rem', sm: '1rem' },
  },
  videoGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
    gap: { xs: '16px', sm: '24px' },
    width: '100%',
    maxWidth: '1200px',
    mx: 'auto',
    mb: { xs: 16, sm: 20 }, // Space for fixed controls
    minHeight: { xs: 'auto', sm: '400px' }, // Ensure minimum height for videos
  },
  videoContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: '16 / 9',
    background: '#1e293b',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.3)',
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'scale(1.02)',
    },
  },
  videoElement: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  localVideo: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transform: 'scaleX(-1)',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  videoLabel: {
    position: 'absolute',
    top: '12px',
    left: '12px',
    background: 'rgba(15, 23, 42, 0.8)',
    backdropFilter: 'blur(8px)',
    borderRadius: '8px',
    px: 2,
    py: 1,
    display: 'flex',
    alignItems: 'center',
    gap: 1,
  },
  labelText: {
    color: '#ffffff',
    fontWeight: 500,
    fontSize: '0.9rem',
  },
  micIndicator: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    animation: 'pulse 1.5s ease-in-out infinite',
  },
  searchingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    background: '#1e293b',
    color: '#ffffff',
  },
  spinnerWrapper: {
    position: 'relative',
    mb: 3,
  },
  searchingText: {
    fontSize: '1.1rem',
    fontWeight: 500,
    mb: 2,
  },
  bounceDots: {
    display: 'flex',
    gap: '8px',
  },
  bounceDot: {
    width: '8px',
    height: '8px',
    background: '#3b82f6',
    borderRadius: '50%',
    animation: 'bounce 0.6s ease-in-out infinite',
  },
  controlsContainer: {
    position: 'fixed',
    bottom: { xs: '16px', sm: '24px' },
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: { xs: '8px', sm: '16px' },
    padding: { xs: '12px 24px', sm: '16px 32px' },
    borderRadius: '20px',
    background: 'rgba(15, 23, 42, 0.9)',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    zIndex: 1000,
  },
  controlButton: {
    width: { xs: 48, sm: 56 },
    height: { xs: 48, sm: 56 },
    borderRadius: '50%',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
    transition: 'all 0.3s ease',
  },
  actionButton: {
    borderRadius: '12px',
    textTransform: 'none',
    fontWeight: 500,
    px: { xs: 2, sm: 3 },
    py: 1.5,
    fontSize: { xs: '0.9rem', sm: '1rem' },
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
    '&:hover': {
      transform: 'scale(1.05)',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.3)',
    },
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  '@keyframes bounce': {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-6px)' },
  },
};